### ISSUE TITLE
求个比特彗星的规则 BitComet

### ISSUE THREAD

**Issue by admans** [Z-Siqi/Clash-for-Windows_Rule#2]
路由器挂的clash，每次用比特彗星下载的时候都需要手动把电脑放在直连，下载完再恢复原样，很麻烦，想用规则让比特彗星直连。谢谢

**Comment by Z-Siqi** [comment]
已添加了 BitComet 相关规则。遗憾的是通过 BitComet 下载时的 link 似乎仍然使用的是原有的下载 link，这意味着Clash的针对链接分配代理的规则无法覆盖到 BitComet 相关 links 之外，即下载的 link 仍然是来自原本网站的
