### ISSUE TITLE
Implicit keys (???)

### ISSUE THREAD

**Issue by EdoJPFV** [Z-Siqi/Clash-for-Windows_Rule#3]
When i try to use the Ubisoft script, it tells me "Implicit keys need to be on a single line at line 7, column 1" (the start of it) how do i fix it??
![image](https://github.com/Z-Siqi/Clash-for-Windows_Rule/assets/56446877/118205e9-252c-4232-8372-252435350f78)
![image](https://github.com/Z-Siqi/Clash-for-Windows_Rule/assets/56446877/30299bad-0dc6-472e-8055-60310526382a)

**Comment by Z-Siqi** [comment]
This rule has mistake, now is fixed.

```
# Ubisoft
- DOMAIN-SUFFIX,ubisoft.com,Ubisoft
- DOMAIN-SUFFIX,ubi.com,Ubisoft
- DOMAIN-SUFFIX,ubisoft.org,Ubisoft
- DOMAIN-SUFFIX,ubisoftconnect.com,Ubisoft
```
